deck36_storm:
    HighFiveStreamJoinBolt:
        main:       "HighFiveStreamJoinBolt.js"
        params:
        rabbitmq:
            exchange:        "plan9"
            routing_key:     "cbt.#"
            target_exchange: "plan9-backchannel"
        badge_timewindow:   35
        badge:
            name: "HighFive"
            text: "Hands up! You used the same cat to solve! Hooray!"
            color:   "red"
            size:    "20px"
            effect:  "explode"


