imports:
    - { resource: storm.yml }

deck36_storm:
    debug:              true
    default_parallelism_hint:    1
    default_num_tasks:   1
    rabbitmq:
        host:           "localhost" #"www.plan9-dev.deck36.de"
        port:           5672
        user:           "guest"
        pass:           "guest"
        vhost:          "/"
        heartbeat:      10
        prefetch:       1
        spout_tasks:    4
    nodejs:
        #executor:          "/usr/bin/node"
        executor:          "/usr/local/bin/node"

    HighFiveStreamJoinBolt:
        main:       "../deck36-api-backend/src/plan9/bolts/HighFiveStreamJoinBolt.js"
        badge_timewindow:   120

